### ISSUE TITLE
1.1 Personal Website - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#13]
### Tasks

* [ ] Create a new Issue with these tasks!
* [ ] Use the Github web interface to create a repository called
  `1.1-Personal-Website`
* [ ] Use the Github web interface to create a branch called on
  `1.1-Personal-Website` called `develop`
* [ ] In Github, open a PR _from_ `develop` _into_ `master`
* [ ] Create your personal website
    * [ ] Checkpoint: Created and committed `index.html`
    * [ ] Checkpoint: Created and committed `main.css`
    * [ ] Complete: Pushed `index.html` and `main.css`

**Comment by jjhampton** [comment]
Personal website created, committed, and pushed.
