### ISSUE TITLE
4.4 github-profile

### ISSUE THREAD

**Issue by skrich-x** [TIY-GVL-FEE-2015-May/assignments#199]
#### Getting Started
* [ ] create repo off scaffold
* [ ] start Gulp
* [ ] generate token in Github
  * [ ] follow instructions on Gatekeeper Github
* [ ] start node server.js

#### AJAX
* [ ] `$.ajax()` requests to:
   * [ ] `https://api.github.com/users/<username>`
   * [ ] `https://api.github.com/users/<username>/repos`

#### TODO - Specific project Tasking
* [ ] console.log repo name, updated at, language, stars and forks
 * [ ] console.log avatar url, name, username, employer, location, email, blog url, join date
 * [ ] Write templates for dynamics sections
   * [ ] User template
   * [ ] List of repositories (single list template with #each, or a li template)
 * [ ] Static HTML
   * [ ] Top content
 * [ ] Dynamic
    * [ ] User container
    * [ ] List container
 * [ ] Style the HTML

#### Requirements
* [ ] Get following information to the DOM:
    * [ ] name
    * [ ] blog
    * [ ] location
    * [ ] email
    * [ ] avatar_url
    * [ ] html_url
    * [ ] and list all of your repositories
