### ISSUE TITLE
4.4 - GitHub Profile - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#202]
## Tasks

- [X] Set up page to work w/ oAuth & Gatekeeper

### Javascript
- [ ] Create function app() to perform AJAX request for GitHub API data
- [ ] Create helper functions that display each major HTML container element to page w/ Handlebars: 
  - [ ] displayTitle()
  - [ ] display Navbar()
  - [ ] displaySidebar()
  - [ ] displayContent() - for repository  information in center of page
  - [ ] refactor all helper functions into one main function displayElement() that can use parameters to display different types of page elements - parameter examples: requiredData, elementName, handlebarsContext

### HTML/CSS
 - [ ] Style page as needed to mirror GitHub visually
