### ISSUE TITLE
5.1 - Constructors and Prototypes - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#214]
## Tasks

- [ ] Create a new Github repo and add exercises.js to it. 

- [ ] Create constructors and methods in that file.

- [ ]  Run the script using node.js to ensure answers are correct.
