### ISSUE TITLE
5.2 - Koans - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#216]
### Tasks

 - [ ] Find the JavaScript koans repository at https://github.com/mrdavidlaing/javascript-koans
 - [ ] Clone the repository and delete the .git directory, or download the .zip file of the repository
 - [ ] Follow the instructions to make all the tests pass.

### Hard Mode

 - [ ] In addition to finishing the koans, try to get through Rebecca Murphey's JavaScript assessment at https://github.com/rmurphey/js-assessment
