### ISSUE TITLE
6.1 - Application Architecture - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#234]
## Tasks
- [ ] [Read Backbone's Getting Started Guide](http://backbonejs.org/#Getting-started)
- [ ] [Read and work through The Backbone Primer](https://github.com/jashkenas/backbone/wiki/Backbone%2C-The-Primer)

- [ ] Watch the "Writing Testable JavaScript" video, and optionally read the
  article
