### ISSUE TITLE
6.1-application-architechure-gj

### ISSUE THREAD

**Issue by badview08** [TIY-GVL-FEE-2015-May/assignments#235]
## Tasks
- [ ] [Read Backbone's Getting Started Guide](http://backbonejs.org/#Getting-started)
- [ ] [Read and work through The Backbone Primer](https://github.com/jashkenas/backbone/wiki/Backbone%2C-The-Primer)

- [ ] Watch the "Writing Testable JavaScript" video, and optionally read the
  article
