### ISSUE TITLE
6.3 - Image Board - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#252]
## Tasks

- [X] Wireframes: Provided by assignment images.  

- [X] Plan Application States
 - [X] Two User screens, w/ Router: 
     - [X] Add & view images screen
     - [X] Hard Mode: User login screen

- [X] Plan Application Domain Model
 Domain Objects: 
 - [X] Post - Image URL, Image caption
 - [X] Post Collection - List of Posts

- [ ] Scaffolding
 - [ ] Clone/create repository locally and on Github
 - [ ] Run setup script
 - [ ] Install Backbone

- [ ] Create Static Mockup 
 - [ ] Create Index.html 
 - [ ] Create Templates for each view element that will be added to DOM
 - [ ] Add Basic CSS styling
 - [ ] Set up main.js to link to index.html and import router / start Backbone history

- [ ] Define Router - router.js

- [ ] Define Collection
 - [ ] Create inside of router

- [ ] Define Model
 - [ ] Image ???
 - [ ] Listen to collection for updates which will rerender the view (.toJSON() ??? )

- [ ] Define Views
 - [ ] Index view - create in router callback
 - [ ] Form view

### Needed files
- [ ] index.html
- [ ] scripts/main.js
- [ ] scripts/router.js
- [ ] scripts/models/image.js
- [ ] scripts/view/index.js
- [ ] templates/index.hbs
