### ISSUE TITLE
8.3 - Soundcloud - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#303]
### Tasks
- [ ] Setup per Assignments page:
 * cd into Assignments directory
 * then ember new <projectName>
 * then hub create <projectName> to create the repo on Github, too

- [ ] Bower install dependencies:
 * Upgrade Ember, Ember-Data
 * Install Ember-CLI-Sass
 * Install Neat, Bourbon
 * Remove .DS_store

- [ ] Get something on page
- [ ] Check that SASS/CSS is working
- [ ] Create static HTML layout within one template
- [ ] Do Codecademy Soundcloud API track
- [ ] Create router / model to bring in needed data ^
- [ ] Generate componenent
