### ISSUE TITLE
1.2 - Blog Layout - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#32]
### Tasks
* [ ] Recreate the following layout in HTML and CSS: https://github.com/TIY-GVL-FEE-2015-May/assignments/blob/master/1.2-blog-layout/blog.png (M)
    * [ ] Generate/allocate project images/fonts/reference materials (S)
    * [ ] Create HTML structure using semantic elements as often as possible (M)
    * [ ] Style HTML w/ appropriate CSS and refactor HTML as needed (L)
* [ ] Commit and push GIT repo to Github (M)
* [ ] Upload a working, publicly visible website with a public URL (i.e. on Github pages,
  with DivShot, on Heroku, etc) (S)
