### ISSUE TITLE
1.4 - Pixel Perfect - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#58]
### Tasks

* **Getting Started**
    * [ ] Follow the assignment instructions to create a new issue. (S)
    * [ ] Follow the assignment instructions to create a new repository. (S)
    * [ ] Create and commit `index.html` (S)
    * [ ] Follow the assignment instructions to create a new pull request. (S)
    * [ ] **Read [this article](http://diveintohtml5.info/semantics.html) about
      semantic HTML.** (S)
* **Slice the Comp**
    Annotate the following images to denote:
      * the tag names and bounding boxes of semantic block-level elements
      * essential CSS properties and values like `margin` and `padding`
      * anything else that will help you execute the design!

    * [ ] Checkpoint: Sliced the page header, annotated and committed! (M)
    * [ ] Checkpoint: Sliced the page footer, annotated and committed! (M)
    * [ ] Checkpoint: Sliced the main article, annotated and committed! (M)
    * [ ] Checkpoint: Sliced the article header, annotated and committed! (M)
    * [ ] Checkpoint: Sliced the article footer, annotated and committed! (M)
    * [ ] Checkpoint: Sliced the sidebar, annotated and committed! (M)
    * [ ] Mission Complete! (M)
* **Code the Comp!**
    * [ ] Checkpoint: Basic HTML structure committed! (S)
    * [ ] Checkpoint: Basic layout CSS committed! (S)
    * [ ] Checkpoint: Pixel perfect page header committed! (M)
    * [ ] Checkpoint: Pixel perfect page footer committed! (M)
    * [ ] Checkpoint: Pixel perfect column layout committed! (M)
    * [ ] Checkpoint: Pixel perfect layout and typography committed! (L)
    * [ ] Checkpoint: Links with hover states committed! (M)
    * [ ] Mission complete! (L)
