### ISSUE TITLE
2.1-git-exercises Gabe Jones

### ISSUE THREAD

**Issue by badview08** [TIY-GVL-FEE-2015-May/assignments#70]
## Tasks
- **Getting Started**
  - [ ] Follow the assignment instructions to create a new issue.
  - [ ] Fork repository `2.1-git-exercises` from the class organization page.
  - [ ] Go through [Learn Git
    Branching](http://pcottle.github.io/learnGitBranching/)
- **Git**
  Using the concepts you learned in the git branching exercise, make the
  following changes to your fork of the assignment repository. You will be
  pulling history from the `develop` branch that already exists.

  - [ ] Create a branch called `exercise-1`. The contents of the branch should
    be `index.html` with only the boilerplate code and the heading.
  - [ ] Create a branch called `exercise-2`. The contents of the branch should
    be `index.html` with only the boilerplate code and the anchor tag.
  - [ ] Create a branch called `exercise-3`. The contents of the branch should
    be `index.html` with all of the content from `develop`, as well as a
    `<h2>` with your name below the `<h2>`. The commit containing your name
    should appear in history immediately after the commit adding the `<h1>`.
  - [ ] Create a branch called `exercise-4`. The contents of the branch should
    be `index.html` with all of the content from `develop`, except the paragraph
    of text should be removed from the page without being removed from the
    branch's history.
  - [ ] Publish your `exercise-3` to GitHub Pages.
