### ISSUE TITLE
2.2 - Responsive Exercises - John Hampton

### ISSUE THREAD

**Issue by jjhampton** [TIY-GVL-FEE-2015-May/assignments#83]
## Tasks

- **Index**

 - [x] Create an index file with links to the other html files

- **Sushi**
Recreate the Sushi layout in HTML and CSS:

- [x] It should have a desktop layout for when the browser is greater than 840px
  wide.
- [x] It should have a tablet layout when the browser is between 840px and 500px
- [x] It should have a mobile layout when the browser is less than 500px.
- [x] The elements should become smaller as the browser shrinks (see video gif)

- **Form**
 - [x] Recreate the Form layout in HTML and CSS:

- **Shirts**
 - [x] Recreate the Shirts layout in HTML and CSS:

 - [x] It should shrink to one column on mobile.
 - [x] `:hover` doesn't work on mobile, so you will need to use another method to
  show the menus on mobile. **Hint:** try looking up `:active`.
